apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: chaosblade
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-3556498
      app-timestamp: test-3556498-902928232
      app-type: deployment
      deploy-name: test
      from-image: "1239381600"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
      creationTimestamp: null
      labels:
        app: test-3556498
        app-timestamp: test-3556498-902928232
        app-type: deployment
        deploy-name: test
        from-image: "1239381600"
    spec:
      automountServiceAccountToken: true
      containers:
      - image: boatswain.registry.si-tech.com.cn:30100/si-tech/tomcat:9.0.13-jdk1.8.0_171-centos7.4
        imagePullPolicy: Always
        lifecycle: {}
        name: test
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

