apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: chaosblades.chaosblade.io
spec:
  group: chaosblade.io
  names:
    kind: ChaosBlade
    listKind: ChaosBladeList
    plural: chaosblades
    singular: chaosblade
    shortNames: [blade]
  scope: Cluster
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                experiments:
                  items:
                    properties:
                      action:
                        type: string
                      desc:
                        type: string
                      matchers:
                        items:
                          properties:
                            name:
                              type: string
                            value:
                              items:
                                type: string
                              type: array
                          required:
                            - name
                            - value
                          type: object
                        type: array
                      scope:
                        type: string
                      target:
                        type: string
                    required:
                      - action
                      - scope
                      - target
                    type: object
                  type: array
              required:
                - experiments
              type: object
            status:
              properties:
                expStatuses:
                  items:
                    properties:
                      action:
                        type: string
                      error:
                        type: string
                      resStatuses:
                        items:
                          properties:
                            error:
                              type: string
                            id:
                              type: string
                            identifier:
                              type: string
                            kind:
                              type: string
                            state:
                              type: string
                            success:
                              type: boolean
                          required:
                            - kind
                            - state
                            - success
                          type: object
                        type: array
                      scope:
                        type: string
                      state:
                        type: string
                      success:
                        type: boolean
                      target:
                        type: string
                    required:
                      - action
                      - scope
                      - state
                      - success
                      - target
                    type: object
                  type: array
                phase:
                  type: string
              required:
                - expStatuses
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
